org: clair99

app: product-microservice

service: cali-product-api

frameworkVersion: "4"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  memorySize: 512

functions:
  product-api-handler:
    handler: handler.product
    events:
      - httpApi: "*"
    environment:
      NODE_ENV: ${env:NODE_ENV}
      MONGO_URI: ${env:AWS_MONGO_URI}

plugins: serverless-offline
