org: clair99

app: product-microservice

service: cali-product-queue

provider:
  name: aws
  runtime: nodejs20.x
  region: af-south-1
  memorySize: 512MB
  environment:
    MONGO_URI: ${env:MONGO_URI}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes

functions:
  producer:
    handler: handler.handle
    events:
      - sqs: arn:aws:sqs:af-south-1:654654412540:Cali_Product_Queue

resources:
  Resources:
    JobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Cali_Product_Queue
