org: clair99

app: product-microservice

service: cali-product-queue

frameworkVersion: "4"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  memorySize: 512

functions:
  product-queue-handler:
    handler: handler.consumer
    events:
      - sqs: arn:aws:sqs:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:Cali_Product_Queue
    environment:
      NODE_ENV: ${env:NODE_ENV}
      MONGO_URI: ${env:AWS_MONGO_URI}

resources:
  Resources:
    JobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: Cali_Product_Queue
