org: clair99

app: product-microservice

service: cali-inventory-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  memorySize: 512

functions:
  inventory-api-handler:
    handler: handler.inventory
    events:
      - httpApi: "*"
    environment:
      NODE_ENV: ${env:NODE_ENV}
      MONGO_URI: ${env:AWS_MONGO_URI}
