org: clair99

app: product-microservice

service: cali-eventbridge

frameworkVersion: "4"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  memorySize: 512

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    environment:
      NODE_ENV: ${env:NODE_ENV}
      MONGO_URI: ${env:MONGO_URI}
